# Enhanced Mean Reversion Pairs Trading Engine Configuration for 2023-2025 Testing

# Data configuration
data:
  symbols:
    - "SPY"
    - "QQQ"
    - "IWM"
    - "EFA"
    - "EMB"
    - "GLD"
    - "SLV"
    - "USO"
    - "TLT"
    - "IEF"
    - "XOM"
    - "CVX"
    - "SLB"
    - "HAL"
    - "MPC"
    - "VLO"
    - "COP"
    - "EOG"
    - "DVN"
    - "ET"
    - "EPD"
    - "OXY"
    - "XLE"
    - "AGG"
    - "PPLT"
    - "UNG"
    - "BNO"
    - "XLK"
    - "SMH"
  start_date: "2023-01-01"
  end_date: "2025-07-01"
  use_cache: false
  force_refresh: false

# Signal generation configuration
signals:
  lookback: 20
  entry_threshold: 1.4
  exit_threshold: 0.2
  max_holding_days: 30
  zscore_window: 20
  entry_quantile: 0.8
  exit_quantile: 0.6
  allow_all_regimes: true
  use_adaptive_thresholds: true
  zscore_quantile_window: 60

# Regime detection configuration
regime:
  hmm_n_components: 3
  regime_volatility_window: 20
  stable_regime_index: 0
  regime_entry_only: false
  allowed_entry_regimes: [0, 1, 2]

# Backtest configuration
backtest:
  initial_capital: 1000000
  target_volatility: 0.15
  slippage_bps: 15.0
  commission_bps: 10.0
  stop_loss_k: 2.0
  zscore_entry_threshold: 1.4
  zscore_exit_threshold: 0.2
  max_hold_days: 20
  target_profit_pct: 0.05
  rebalance_freq: 21
  max_concurrent_positions: 5
  execution_timing: false
  execution_penalty_factor: 1.05
  behavioral_execution: false
  include_unhealthy_pairs: false
  health_strict_mode: false
  stress_filtering: false

# Enhanced metrics configuration
metrics:
  risk_free_rate: 0.04  # Updated for 2023-2025 period
  confidence_level: 0.95
  periods_per_year: 252
  benchmark_sharpe: 1.0

# Statistical thresholds for enhanced pair selection
statistical:
  adf_pvalue_max: 0.15
  coint_pvalue_max: 0.15
  r_squared_min: 0.5
  correlation_min: 0.55
  hurst_threshold: 0.65
  min_observations: 252

# Pair selection configuration
pair_selection:
  min_correlation: 0.4
  correlation_window: 60
  min_spread_stability: 0.3
  spread_stability_window: 60
  max_zscore_volatility: 2.0
  min_cointegration_stability: 0.2
  stability_lookback: 20
  min_data_points: 100
  top_n_pairs: 5
  sector_filter_enabled: false
  min_pair_sharpe: 0.5

# Scoring weights for pair selection
scoring_weights:
  cointegration: 0.3
  hurst: 0.2
  adf: 0.15
  zscore_vol: 0.15
  correlation: 0.1
  spread_stability: 0.1

# Disable regime filtering to avoid errors
regime_filtering:
  enabled: false
  use_vix_filter: false
  use_trend_filter: false
  use_rolling_sharpe_filter: false
  use_market_regime_filter: false

# Legacy parameters
START_DATE: "2023-01-01"
END_DATE: "2025-07-01"
use_cache: false
force_refresh: false 