# Enhanced Mean Reversion Pairs Trading Engine Configuration

# Data configuration
data:
  symbols:
    - "SPY"
    - "QQQ"
    - "IWM"
    - "EFA"
    - "EMB"
    - "GLD"
    - "SLV"
    - "USO"
    - "TLT"
    - "IEF"
    - "XOM"
    - "CVX"
    - "SLB"
    - "HAL"
    - "MPC"
    - "VLO"
    - "COP"
    - "EOG"
    - "DVN"
    - "ET"
    - "EPD"
    - "OXY"
    - "XLE"
    - "AGG"
    - "PPLT"
    - "UNG"
    - "BNO"
    - "XLK"
    - "SMH"
  start_date: "2018-01-01"
  end_date: "2024-12-31"
  use_cache: false
  force_refresh: false

# Signal generation configuration
signals:
  lookback: 20
  entry_threshold: 2.0
  exit_threshold: 0.5
  max_holding_days: 30
  zscore_window: 20
  entry_quantile: 0.9
  exit_quantile: 0.5
  allow_all_regimes: true
  use_adaptive_thresholds: true
  zscore_quantile_window: 60

# Regime detection configuration
regime:
  hmm_n_components: 3
  regime_volatility_window: 20
  stable_regime_index: 0
  regime_entry_only: true
  allowed_entry_regimes: [0, 1]

# Backtest configuration
backtest:
  initial_capital: 1000000
  target_volatility: 0.15
  slippage_bps: 5.0
  commission_bps: 10.0
  stop_loss_k: 2.0
  zscore_entry_threshold: 1.5
  zscore_exit_threshold: 0.5
  max_hold_days: 15
  target_profit_pct: 0.05
  rebalance_freq: 21
  max_concurrent_positions: 5
  regime_scaling: true
  regime_volatility_multiplier: 1.0
  regime_trend_multiplier: 1.0

# Enhanced metrics configuration
metrics:
  risk_free_rate: 0.02
  confidence_level: 0.95
  periods_per_year: 252
  benchmark_sharpe: 1.0

# Statistical thresholds for enhanced pair selection
statistical:
  adf_pvalue_max: 0.05
  coint_pvalue_max: 0.05
  r_squared_min: 0.7
  correlation_min: 0.8
  hurst_threshold: 0.5
  min_observations: 252

# Pair selection configuration
pair_selection:
  min_correlation: 0.5
  correlation_window: 60
  min_spread_stability: 0.4
  spread_stability_window: 60
  max_zscore_volatility: 1.8
  min_cointegration_stability: 0.3
  stability_lookback: 20
  min_data_points: 100
  top_n_pairs: 5
  sector_filter_enabled: true
  min_pair_sharpe: 0.8

# Scoring weights for pair selection
scoring_weights:
  cointegration: 0.3
  hurst: 0.2
  adf: 0.15
  zscore_vol: 0.15
  correlation: 0.1
  spread_stability: 0.1

# Risk management configuration
risk_management:
  stop_loss:
    mode: "atr"
    atr_lookback: 20
    atr_multiplier: 2.0
    fixed_multiplier: 0.02
  
  skew_filter:
    enabled: true
    lookback: 60
    min_down_up_ratio: 0.5
    min_sortino: 0.5
  
  position_sizing:
    regime_aware: true
    base_size: 0.1
    regime_multipliers:
      high_volatility: 0.5
      low_volatility: 1.5
      transition: 1.0
  
  risk_metrics:
    risk_free_rate: 0.02
    benchmark_sharpe: 1.0

# Risk control configuration
risk_control:
  atr_multiplier: 2.0
  atr_period: 14
  max_drawdown_per_pair: 0.05
  max_drawdown_per_trade: 0.02
  max_pair_exposure: 0.1
  volatility_scaling: true
  max_pct_portfolio: 0.10
  max_leverage: 2.0
  max_total_exposure: 1.5
  max_concurrent_trades_per_pair: 2
  min_risk_reward_ratio: 1.5
  max_correlation_exposure: 0.3

# Sector mapping
sector_map:
  XOM: Energy
  CVX: Energy
  SLB: Energy
  HAL: Energy
  MPC: Energy
  VLO: Energy
  COP: Energy
  EOG: Energy
  DVN: Energy
  ET: Energy
  EPD: Energy
  OXY: Energy

# Manual pair list
manual_pair_list:
  - ["XOM", "CVX"]
  - ["COP", "XOM"]
  - ["SLB", "HAL"]
  - ["MPC", "VLO"]
  - ["EOG", "DVN"]

# Pair-specific parameters
pair_params:
  XOM_CVX:
    entry_threshold: 1.5
    exit_threshold: 0.5
    stop_loss_k: 2.0
    max_holding_days: 20
    min_days_between_trades: 5
    profit_target_pct: 0.02
  COP_XOM:
    entry_threshold: 1.5
    exit_threshold: 0.4
    stop_loss_k: 2.2
    max_holding_days: 15
    min_days_between_trades: 7
    profit_target_pct: 0.015

# Grid search parameters
grid_search:
  entry_thresholds: [1.5, 2.0, 2.5]
  exit_thresholds: [0.1, 0.2, 0.3]
  stop_loss_ks: [2.0, 2.5, 3.0]

# Walk-forward validation parameters
walkforward:
  train_months: 24
  test_months: 6
  z_entry_values: [1.0, 1.5, 2.0]
  z_exit_values: [0.5, 0.0]
  scoring_metric: sharpe_ratio

# Legacy parameters (for backward compatibility)
ETF_TICKERS:
  - "SPY"
  - "QQQ"
  - "IWM"
  - "EFA"
  - "EMB"
  - "GLD"
  - "SLV"
  - "USO"
  - "TLT"
  - "IEF"
  - "XOM"
  - "CVX"
  - "SLB"
  - "HAL"
  - "MPC"
  - "VLO"
  - "COP"
  - "EOG"
  - "DVN"
  - "ET"
  - "EPD"
  - "OXY"
  - "XLE"
  - "AGG"
  - "PPLT"
  - "UNG"
  - "BNO"
  - "XLK"
  - "SMH"
START_DATE: "2018-01-01"
END_DATE: "2024-12-31"
use_cache: false
force_refresh: false
COINTEGRATION_WINDOW: 60
COINTEGRATION_PVALUE_THRESHOLD: 0.15
ZSCORE_WINDOW: 20
HMM_N_COMPONENTS: 3
REGIME_VOLATILITY_WINDOW: 20
STABLE_REGIME_INDEX: 0
TOP_N_PAIRS: 5
SECTOR_FILTER_ENABLED: true
ALLOW_ALL_REGIMES: true
USE_ADAPTIVE_THRESHOLDS: true
ZSCORE_QUANTILE_WINDOW: 60
ENTRY_QUANTILE: 0.9
EXIT_QUANTILE: 0.5
MIN_PAIR_SHARPE: 0.8
REGIME_ENTRY_ONLY: true
ALLOWED_ENTRY_REGIMES: [0, 1]
min_days_between_trades: 5
