# Enhanced Mean Reversion Pairs Trading Engine Configuration

# Data configuration
data:
  symbols:
    - "SPY"
    - "QQQ"
    - "IWM"
    - "EFA"
    - "EMB"
    - "GLD"
    - "SLV"
    - "USO"
    - "TLT"
    - "IEF"
    - "XOM"
    - "CVX"
    - "SLB"
    - "HAL"
    - "MPC"
    - "VLO"
    - "COP"
    - "EOG"
    - "DVN"
    - "ET"
    - "EPD"
    - "OXY"
    - "XLE"
    - "AGG"
    - "PPLT"
    - "UNG"
    - "BNO"
    - "XLK"
    - "SMH"
  start_date: "2018-01-01"
  end_date: "2024-12-31"
  use_cache: false
  force_refresh: false

# Signal generation configuration
signals:
  lookback: 20
  entry_threshold: 1.4
  exit_threshold: 0.2
  max_holding_days: 30
  zscore_window: 20
  entry_quantile: 0.8
  exit_quantile: 0.6
  allow_all_regimes: true
  use_adaptive_thresholds: true
  zscore_quantile_window: 60
  
  # Dynamic threshold adjustments
  adaptive_thresholds:
    enabled: true
    volatility_scaling: true
    spread_volatility_window: 60
    volatility_multiplier: 1.5  # Scale thresholds by recent volatility
    
    # Market condition adjustments
    high_vol_multiplier: 1.2   # Higher thresholds in high vol
    low_vol_multiplier: 0.8    # Lower thresholds in low vol
    trend_adjustment: true     # Adjust for trending markets
    
    # Signal confidence
    min_signal_confidence: 0.6  # Minimum confidence for trade entry
    kalman_filter_enabled: true # Use Kalman filter for mean estimation

# Regime detection configuration
regime:
  hmm_n_components: 3
  regime_volatility_window: 20
  stable_regime_index: 0
  regime_entry_only: true
  allowed_entry_regimes: [0, 1]

# Backtest configuration
backtest:
  initial_capital: 1000000
  target_volatility: 0.15
  slippage_bps: 15.0
  commission_bps: 10.0
  stop_loss_k: 2.0
  zscore_entry_threshold: 1.4
  zscore_exit_threshold: 0.2
  max_hold_days: 20
  target_profit_pct: 0.05
  rebalance_freq: 21
  max_concurrent_positions: 5
  risk_control:
    atr_multiplier: 2.0
    atr_period: 14
    max_drawdown_per_pair: 0.05
    max_drawdown_per_trade: 0.02
    max_pair_exposure: 0.1
    volatility_target: 0.15
  
  # Dynamic position sizing
  volatility_targeting: true
  target_pair_volatility: 0.20
  position_size_method: "volatility_scaled"
  max_position_size: 0.15
  
  # Risk management
  max_drawdown_per_pair: 0.10
  max_portfolio_drawdown: 0.20
  correlation_threshold: 0.70

# Enhanced metrics configuration
metrics:
  risk_free_rate: 0.02
  confidence_level: 0.95
  periods_per_year: 252
  benchmark_sharpe: 1.0

# Statistical thresholds for enhanced pair selection
statistical:
  adf_pvalue_max: 0.15
  coint_pvalue_max: 0.15
  r_squared_min: 0.5
  correlation_min: 0.55
  hurst_threshold: 0.65
  min_observations: 252

# Pair selection configuration
pair_selection:
  min_correlation: 0.4
  correlation_window: 60
  min_spread_stability: 0.3
  spread_stability_window: 60
  max_zscore_volatility: 2.0
  min_cointegration_stability: 0.2
  stability_lookback: 20
  min_data_points: 100
  top_n_pairs: 5
  sector_filter_enabled: false
  min_pair_sharpe: 0.5

# Scoring weights for pair selection
scoring_weights:
  cointegration: 0.3
  hurst: 0.2
  adf: 0.15
  zscore_vol: 0.15
  correlation: 0.1
  spread_stability: 0.1

# Risk management configuration
risk_management:
  stop_loss:
    mode: "atr"
    atr_lookback: 20
    atr_multiplier: 2.0
    fixed_multiplier: 0.02
  
  skew_filter:
    enabled: true
    lookback: 60
    min_down_up_ratio: 0.5
    min_sortino: 0.5
  
  position_sizing:
    regime_aware: true
    base_size: 0.1
    regime_multipliers:
      high_volatility: 0.5
      low_volatility: 1.5
      transition: 1.0
  
  risk_metrics:
    risk_free_rate: 0.02
    benchmark_sharpe: 1.0

# Risk control configuration
risk_control:
  atr_multiplier: 2.0
  atr_period: 14
  max_drawdown_per_pair: 0.05
  max_drawdown_per_trade: 0.02
  max_pair_exposure: 0.1
  volatility_scaling: true
  max_pct_portfolio: 0.10
  max_leverage: 2.0
  max_total_exposure: 1.5
  max_concurrent_trades_per_pair: 2
  min_risk_reward_ratio: 1.5
  max_correlation_exposure: 0.3

# Sector mapping
sector_map:
  XOM: Energy
  CVX: Energy
  SLB: Energy
  HAL: Energy
  MPC: Energy
  VLO: Energy
  COP: Energy
  EOG: Energy
  DVN: Energy
  ET: Energy
  EPD: Energy
  OXY: Energy

# Manual pair list
manual_pair_list:
  - ["XOM", "CVX"]
  - ["COP", "XOM"]
  - ["SLB", "HAL"]
  - ["MPC", "VLO"]
  - ["EOG", "DVN"]

# Pair-specific parameters
pair_params:
  XOM_CVX:
    entry_threshold: 1.5
    exit_threshold: 0.5
    stop_loss_k: 2.0
    max_holding_days: 20
    min_days_between_trades: 5
    profit_target_pct: 0.02
  COP_XOM:
    entry_threshold: 1.5
    exit_threshold: 0.4
    stop_loss_k: 2.2
    max_holding_days: 15
    min_days_between_trades: 7
    profit_target_pct: 0.015

# Grid search parameters
grid_search:
  entry_thresholds: [1.5, 2.0, 2.5]
  exit_thresholds: [0.1, 0.2, 0.3]
  stop_loss_ks: [2.0, 2.5, 3.0]

# Walk-forward validation parameters
walkforward:
  train_months: 24
  test_months: 6
  z_entry_values: [1.0, 1.5, 2.0]
  z_exit_values: [0.5, 0.0]
  scoring_metric: sharpe_ratio

# Legacy parameters (for backward compatibility)
ETF_TICKERS:
  - "SPY"
  - "QQQ"
  - "IWM"
  - "EFA"
  - "EMB"
  - "GLD"
  - "SLV"
  - "USO"
  - "TLT"
  - "IEF"
  - "XOM"
  - "CVX"
  - "SLB"
  - "HAL"
  - "MPC"
  - "VLO"
  - "COP"
  - "EOG"
  - "DVN"
  - "ET"
  - "EPD"
  - "OXY"
  - "XLE"
  - "AGG"
  - "PPLT"
  - "UNG"
  - "BNO"
  - "XLK"
  - "SMH"
START_DATE: "2018-01-01"
END_DATE: "2024-12-31"
use_cache: false
force_refresh: false
COINTEGRATION_WINDOW: 60
COINTEGRATION_PVALUE_THRESHOLD: 0.15
ZSCORE_WINDOW: 20
HMM_N_COMPONENTS: 3
REGIME_VOLATILITY_WINDOW: 20
STABLE_REGIME_INDEX: 0
TOP_N_PAIRS: 5
SECTOR_FILTER_ENABLED: true
ALLOW_ALL_REGIMES: true
USE_ADAPTIVE_THRESHOLDS: true
ZSCORE_QUANTILE_WINDOW: 60
ENTRY_QUANTILE: 0.9
EXIT_QUANTILE: 0.5
MIN_PAIR_SHARPE: 0.8
REGIME_ENTRY_ONLY: true
ALLOWED_ENTRY_REGIMES: [0, 1]
min_days_between_trades: 5

# Regime detection and filtering
regime_detection:
  enabled: true
  method: "vix_based"  # Options: vix_based, hmm, trend_filter
  vix_threshold_high: 25.0  # High volatility regime threshold
  vix_threshold_low: 15.0   # Low volatility regime threshold
  
  # Regime-specific adjustments
  high_volatility_multiplier: 0.5  # Reduce position size in high vol
  low_volatility_multiplier: 1.2   # Increase position size in low vol
  trend_regime_threshold: 0.6      # Disable reversion if trend > 0.6
  
  # Market regime indicators
  use_vix_filter: true
  use_trend_filter: true
  use_sentiment_filter: false  # Future enhancement

# Enhanced regime filtering configuration
regime_filtering:
  enabled: true
  
  # VIX-based volatility filtering
  use_vix_filter: true
  vix_threshold_high: 25.0
  vix_threshold_low: 15.0
  vix_lookback: 5  # Days to average VIX
  
  # Trend-based filtering
  use_trend_filter: true
  trend_window: 60
  trend_slope_threshold: 0.6
  trend_ma_window: 20
  
  # Rolling Sharpe ratio filtering
  use_rolling_sharpe_filter: true
  rolling_sharpe_window: 60
  rolling_sharpe_min: 0.2
  rolling_sharpe_lookback: 252  # 1 year
  
  # Market condition filters
  use_market_regime_filter: true
  market_regime_window: 20
  min_regime_stability: 0.7
  
  # Position sizing based on regime
  regime_position_sizing:
    high_volatility_multiplier: 0.5
    low_volatility_multiplier: 1.5
    trending_multiplier: 0.3
    mean_reverting_multiplier: 1.0
