ETF_TICKERS:
  - "SPY"
  - "QQQ"
  - "IWM"
  - "EFA"
  - "EMB"
  - "GLD"
  - "SLV"
  - "USO"
  - "TLT"
  - "IEF"
  - "XOM"
  - "CVX"
  - "SLB"
  - "HAL"
  - "MPC"
  - "VLO"
  - "COP"
  - "EOG"
  - "DVN"
  - "ET"
  - "EPD"
  - "OXY"
START_DATE: "2018-01-01"
END_DATE: "2024-12-31"
use_cache: false
force_refresh: false
COINTEGRATION_WINDOW: 60
COINTEGRATION_PVALUE_THRESHOLD: 0.15
ZSCORE_WINDOW: 20
HMM_N_COMPONENTS: 3
REGIME_VOLATILITY_WINDOW: 20
STABLE_REGIME_INDEX: 0
TOP_N_PAIRS: 5
SECTOR_FILTER_ENABLED: true
SECTOR_MAP:
  XOM: Energy
  CVX: Energy
  SLB: Energy
  HAL: Energy
  MPC: Energy
  VLO: Energy
  COP: Energy
  EOG: Energy
  DVN: Energy
  ET: Energy
  EPD: Energy
  OXY: Energy
MANUAL_PAIR_LIST:
  - ["XOM", "CVX"]
  - ["COP", "XOM"]
  - ["SLB", "HAL"]
  - ["MPC", "VLO"]
  - ["EOG", "DVN"]
PAIR_PARAMS:
  XOM_CVX:
    entry_threshold: 1.5
    exit_threshold: 0.5
    stop_loss_k: 2.0
    max_holding_days: 20
    min_days_between_trades: 5
    profit_target_pct: 0.02
  COP_XOM:
    entry_threshold: 1.5
    exit_threshold: 0.4
    stop_loss_k: 2.2
    max_holding_days: 15
    min_days_between_trades: 7
    profit_target_pct: 0.015

# Configuration for the backtester
backtest:
  initial_capital: 1000000
  target_volatility: 0.15
  slippage_bps: 5.0
  commission_bps: 10.0
  stop_loss_k: 2.0
  zscore_entry_threshold: 1.5
  zscore_exit_threshold: 0.5
  max_hold_days: 15
  target_profit_pct: 0.05
  rebalance_freq: 21
  max_concurrent_positions: 5

# Parameter ranges for CLI grid search
grid_search:
  entry_thresholds: [1.5, 2.0, 2.5]
  exit_thresholds: [0.1, 0.2, 0.3]
  stop_loss_ks: [2.0, 2.5, 3.0]

# Trading Parameters
ALLOW_ALL_REGIMES: true
USE_ADAPTIVE_THRESHOLDS: true
ZSCORE_QUANTILE_WINDOW: 60
ENTRY_QUANTILE: 0.9
EXIT_QUANTILE: 0.5

# Minimum Sharpe ratio for pair inclusion
MIN_PAIR_SHARPE: 0.8

# Regime entry constraint
REGIME_ENTRY_ONLY: true

# Regimes allowed for entry (list)
ALLOWED_ENTRY_REGIMES: [0, 1]

# Risk Management
min_days_between_trades: 5

# Walk-forward validation parameters
WALKFORWARD_TRAIN_MONTHS: 18
WALKFORWARD_TEST_MONTHS: 6
WALKFORWARD_STEP_MONTHS: 6

risk_management:
  # Stop-loss settings
  stop_loss:
    mode: "atr"  # Options: "fixed", "atr"
    atr_lookback: 20  # Lookback period for ATR calculation
    atr_multiplier: 2.0  # Multiplier for ATR-based stop-loss
    fixed_multiplier: 0.02  # Fixed stop-loss percentage (2%)
  
  # Skew filter settings
  skew_filter:
    enabled: true
    lookback: 60  # Days to look back for skew calculation
    min_down_up_ratio: 0.5  # Minimum acceptable downside/upside ratio
    min_sortino: 0.5  # Minimum acceptable Sortino ratio
  
  # Position sizing settings
  position_sizing:
    regime_aware: true  # Adjust position size based on market regime
    base_size: 0.1  # Base position size (10% of portfolio)
    regime_multipliers:
      high_volatility: 0.5  # Reduce size in high volatility
      low_volatility: 1.5  # Increase size in low volatility
      transition: 1.0  # Normal size in transition periods
  
  # Risk metrics
  risk_metrics:
    risk_free_rate: 0.02  # Annual risk-free rate (2%)
    benchmark_sharpe: 1.0  # Benchmark Sharpe ratio for PSR calculation

# Pair Selection and Filtering Parameters
PAIR_SELECTION:
  min_correlation: 0.5
  correlation_window: 60
  min_spread_stability: 0.4
  spread_stability_window: 60
  max_zscore_volatility: 1.8
  min_cointegration_stability: 0.3
  stability_lookback: 20
  min_data_points: 100

# Enhanced scoring weights
SCORING_WEIGHTS:
  cointegration: 0.3
  hurst: 0.2
  adf: 0.15
  zscore_vol: 0.15
  correlation: 0.1
  spread_stability: 0.1

pair_scoring:
  weights:
    correlation: 0.25
    coint_p: 0.25
    hurst: 0.25
    zscore_vol: 0.25

# Curated Pair Universes
PAIR_UNIVERSES:
  energy:
    description: "Energy sector ETFs"
    pairs:
      - ["XLE", "XOM"]
      - ["XLE", "CVX"]
      - ["XOM", "CVX"]
    min_correlation: 0.5
    min_spread_stability: 0.4
    max_zscore_volatility: 1.8
    min_cointegration_stability: 0.3

  bonds:
    description: "Bond ETFs"
    pairs:
      - ["TLT", "IEF"]
      - ["TLT", "AGG"]
      - ["IEF", "AGG"]
    min_correlation: 0.5
    min_spread_stability: 0.4
    max_zscore_volatility: 1.8
    min_cointegration_stability: 0.3

  metals:
    description: "Precious metals ETFs"
    pairs:
      - ["GLD", "SLV"]
      - ["GLD", "PPLT"]
      - ["SLV", "PPLT"]
    min_correlation: 0.5
    min_spread_stability: 0.4
    max_zscore_volatility: 1.8
    min_cointegration_stability: 0.3

  energy_proxy:
    description: "Energy proxy ETFs"
    pairs:
      - ["UNG", "USO"]
      - ["UNG", "BNO"]
      - ["USO", "BNO"]
    min_correlation: 0.5
    min_spread_stability: 0.4
    max_zscore_volatility: 1.8
    min_cointegration_stability: 0.3

  tech:
    description: "Technology sector ETFs"
    pairs:
      - ["XLK", "QQQ"]
      - ["XLK", "SMH"]
      - ["QQQ", "SMH"]
    min_correlation: 0.5
    min_spread_stability: 0.4
    max_zscore_volatility: 1.8
    min_cointegration_stability: 0.3

# Visualization settings
visualization:
  save_plots: true
  plot_types:
    - "correlation"
    - "spread"
    - "zscore"
    - "cointegration"
    - "stability"
  plot_params:
    correlation_window: 60
    spread_window: 60
    zscore_window: 20
    cointegration_window: 60
    stability_window: 120
  output_dir: "reports/plots"
